Fixing the yaml.
Signed-off-by: florian-schaeffeler <florian.schaeffeler@leica-geosystems.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,72 +1,71 @@
 ---
 name: CI
-'on':
-    pull_request:
-    push:
+"on":
+  pull_request:
+  push:
     branches:
-        - main
-    schedule:
+      - main
+  schedule:
     - cron: "0 5 * * 4"
 
 jobs:
-
-    lint:
+  lint:
     name: Lint
     runs-on: ubuntu-latest
     steps:
-        - name: Check out the codebase.
+      - name: Check out the codebase.
         uses: actions/checkout@v2
 
-        - name: Set up Python 3.
+      - name: Set up Python 3.
         uses: actions/setup-python@v2
         with:
-            python-version: '3.x'
+          python-version: "3.x"
 
-        - name: Install test dependencies.
+      - name: Install test dependencies.
         run: pip3 install yamllint ansible ansible-lint
 
-        - name: Lint code.
+      - name: Lint code.
         run: |
-            yamllint .
-            ansible-lint
+          yamllint .
+          ansible-lint
 
-    integration:
+  integration:
     name: Integration
     runs-on: ${{ matrix.os }}
     strategy:
-        matrix:
+      matrix:
         os:
-            - ubuntu-24.04
-            - ubuntu-22.04
+          - ubuntu-22.04
+          - ubuntu-24.04
 
     steps:
-        - name: Check out the codebase.
-        uses: actions/checkout@v4
+      - name: Check out the codebase.
+        uses: actions/checkout@v2
 
-        - name: Install test dependencies.
+      - name: Install test dependencies.
         run: |
-            sudo pip3 install --upgrade pip
-            sudo pip3 install ansible
+          sudo pip3 install --upgrade pip
+          sudo pip3 install ansible
 
-        - name: Set up the test environment.
+      - name: Set up the test environment.
         run: |
-            cp tests/ansible.cfg ./ansible.cfg
-            cp tests/inventory ./inventory
-            cp tests/config.yml ./config.yml
-            ansible-galaxy install -r requirements.yml
+          cp tests/ansible.cfg ./ansible.cfg
+          cp tests/inventory ./inventory
+          cp tests/config.yml ./config.yml
+          ansible-galaxy install -r requirements.yml
 
-        - name: Test the playbook's syntax.
+      - name: Test the playbook's syntax.
         run: ansible-playbook main.yml --syntax-check
 
-        - name: Test the playbook.
+      - name: Test the playbook.
         run: ansible-playbook main.yml
         env:
-            ANSIBLE_FORCE_COLOR: '1'
+          ANSIBLE_FORCE_COLOR: "1"
 
-        - name: Idempotence check.
+      - name: Idempotence check.
         run: |
-            idempotence=$(mktemp)
-            ansible-playbook main.yml | tee -a ${idempotence}
-            tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+          idempotence=$(mktemp)
+          ansible-playbook main.yml | tee -a ${idempotence}
+          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
         env:
-            ANSIBLE_FORCE_COLOR: '1'
+          ANSIBLE_FORCE_COLOR: "1"
